### ISSUE TITLE
运行报错，这个是什么原因呢，谢谢

### ISSUE THREAD

**Issue by ximencx** [NeglectedByBoss/MouseView_TV#2]
```
03-20 03:34:27.537 6410-6410/com.tamic.tvmouse E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.tamic.tvmouse, PID: 6410
                                                                 java.lang.StackOverflowError
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:132)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:148)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:148)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:148)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:148)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:148)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:148)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:148)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                     at com.tamic.tvmouse.TcMouseManager.onDpadClicked(TcMouseManager.java:148)
                                                                     at com.tamic.tvmouse.TcMouseManager.onclick(TcMouseManager.java:214)
                                                                     at com.tamic.tvmouse.TcMouseView.dispatchKeyEvent(TcMouseView.java:148)
                                                                     at com.tamic.tvmouse.TcMouseView.scrollView(TcMouseView.java:110)
                                                                     at com.tamic.tvmouse.TcMouseView.moveMouse(TcMouseView.java:167)
                                                                     at com.tamic.tvmouse.TcMouseManager.dispatchKeyEventToMouse(TcMouseManager.java:164)
                                                                 	at com.tamic.tvmouse.TcMous
```

**Comment by Tamicer** [comment]
@ximencx  刚启动还是运行很久后出现的？

**Comment by ximencx** [comment]
@Tamicer  api19系统运行，启动后把鼠标一直往上移动，到了状态栏就包这个错，而且点击不管用

**Comment by aibiaoxiaoyu** [comment]
> @Tamicer api19系统运行，启动后把鼠标一直往上移动，到了状态栏就包这个错，而且点击不管用

这个是代码问题，出现了死循环，鼠标在边界的时候
